name: "test"

on: ["workflow_dispatch"]

jobs:
  eap:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-python@v4.7.1"
      - run: |
          pip install ruff
          ruff --foo
        shell: "pwsh"
  neap:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-python@v4.7.1"
      - run: |
          $PSNativeCommandUseErrorActionPreference = $false
          pip install ruff
          ruff --foo
        shell: "pwsh"
